# Generated by Django 3.1.6 on 2021-02-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(max_length=1000)),
                ('starting_bid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.ImageField(blank=True, height_field=300, upload_to='gallery', width_field=300)),
                ('category', models.CharField(choices=[('F', 'Fashion'), ('T', 'Toys'), ('E', 'Electronics'), ('H', 'Home'), ('S', 'Sports'), ('P', 'Pets'), ('M', 'Miscellaneous')], default='M', max_length=13)),
            ],
        ),
        migrations.DeleteModel(
            name='Listings',
        ),
    ]
