# Generated by Django 3.1.6 on 2021-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20210222_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listed_by',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
