# Generated by Django 3.1.6 on 2021-02-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_auto_20210222_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listed_by',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
