# Generated by Django 3.1.6 on 2021-03-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_bids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='starting_bid',
        ),
        migrations.AddField(
            model_name='bids',
            name='max_bid',
            field=models.FloatField(default=0.0),
        ),
    ]
