# Generated by Django 3.1.6 on 2021-03-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.CharField(default='False', max_length=64),
            preserve_default=False,
        ),
    ]
